defaults:
  - logger: ~
  - callbacks:
    - progressbar
    - early_stopping
    - weights_summary
    # - swa
  - override /hydra/job_logging@_global_.hydra.job_logging: nofile

hydra:
  job:
    env_set:
      DEBUG_MODE: '1'

_target_: src.utility.fn.instantiate_trainer

fast_dev_run: 3
checkpoint_callback: false

gpus: 1
gradient_clip_val: 5.
track_grad_norm: -1
# max_epochs: 1000 # due to fast_dev_run
max_steps: -1
val_check_interval: 1.0 # int for n epoch, float for in epoch
accumulate_grad_batches: 1
precision: 32
# num_sanity_val_steps: 2 # due to fast_dev_run
resume_from_checkpoint: ~
detect_anomaly: true
deterministic: false

# following are settings you should not touch in most cases
accelerator: ${accelerator:${.gpus}}
replace_sampler_ddp: false
multiple_trainloader_mode: min_size
enable_model_summary: false