defaults:
  - logger: ~
  - callbacks:
    - progressbar
  - override /hydra/job_logging@_global_.hydra.job_logging: nofile

_target_: src.utility.fn.instantiate_trainer

enable_checkpointing: false
logger: ~

gpus: 1
precision: 32
resume_from_checkpoint: ~

# following are settings you should not touch in most cases
accelerator: ${accelerator:${.gpus}}
detect_anomaly: false
replace_sampler_ddp: false
enable_model_summary: false
