# some cfg should not belong to any submodule
seed: ~
project: untitled
name: ${name_guard:@@@AUTO@@@}
watch_field: val/loss
watch_mode: min
root: ${hydra:runtime.cwd}
load_cfg_from_checkpoint: ~

pipeline:
  _target_: src.pipeline.Pipeline

  load_from_checkpoint: ~
  loss_reduction_mode: token

hydra:
  sweep:
    dir: outputs/multirun/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${path_guard:${hydra.job.override_dirname}}
  run:
    dir: outputs/${path_guard:${name}}/${now:%Y-%m-%d_%H-%M-%S}
  output_subdir: config
  job:
    env_set:
      TOKENIZERS_PARALLELISM: 'false'
      HF_DATASETS_OFFLINE: '1'
      TRANSFORMERS_OFFLINE: '1'
      TORCH_WARN_ONCE: '1'
      NUMEXPR_MAX_THREADS: '8'
      DEBUG_MODE: '0'

defaults:
  - _self_
  - trainer: train
  - data: vlparse
  - model: vlgae