# @package hydra.job_logging

version: 1
formatters:
  console:
    (): src.utility.logger.ColorFormatter
    format: '[%(name)s] %(message)s'
handlers:
  console:
    class: src.utility.logger.TqdmLoggingHandler
    formatter: console
    level: DEBUG
root:
  handlers: [console]
loggers:
  fastNLP:
    handlers: [console]
  lightning:
    handlers: [console]
  nni:
    handlers: [console]
disable_existing_loggers: false
